/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddHousePanel.java
 *
 * Created on 17.Kas.2009, 21:52:50
 */

package fairhelper.panels;

import fairhelper.House;
import fairhelper.HouseManager;
import fairhelper.Settings;
import fairhelper.language.Language;
import fairhelper.theme.Theme;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Feoran
 */
public class AddHousePanel extends javax.swing.JPanel {

    /** Creates new form AddHousePanel */
    public AddHousePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addHousePanelHouseNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addHousePanelKiraCheck = new javax.swing.JCheckBox();
        addHousePanelKendiCheck = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        addHousePanelHouseTypeCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        addHousePanelIsınmaCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        addHousePanelGelirCombo = new javax.swing.JComboBox();
        addHousePanelAddButton = new javax.swing.JButton();
        addHousePanelBackButton = new javax.swing.JButton();

        setBackground(Theme.getColor("backgroundColor2"));
        setPreferredSize(new java.awt.Dimension(620, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(Theme.getColor("labelColor1"));
        jLabel1.setText(Language.getText("houseNameLabel"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(Theme.getColor("labelColor1"));
        jLabel2.setText(Language.getText("addHousePanelMainLabel"));

        addHousePanelHouseNameField.setBackground(Theme.getColor("fieldBackgroundColor1"));
        addHousePanelHouseNameField.setForeground(Theme.getColor("fieldForegroundColor1"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(Theme.getColor("labelColor1"));
        jLabel3.setText(Language.getText("houseStateLabel"));

        addHousePanelKiraCheck.setBackground(Theme.getColor("backgroundColor2"));
        addHousePanelKiraCheck.setForeground(Theme.getColor("labelColor1"));
        addHousePanelKiraCheck.setText(Language.getText("addHouseRentalLabel"));
        addHousePanelKiraCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHousePanelKiraCheckActionPerformed(evt);
            }
        });

        addHousePanelKendiCheck.setBackground(Theme.getColor("backgroundColor2"));
        addHousePanelKendiCheck.setForeground(Theme.getColor("labelColor1"));
        addHousePanelKendiCheck.setText(Language.getText("addHouseOwnHouseLabel"));
        addHousePanelKendiCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHousePanelKendiCheckActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(Theme.getColor("labelColor1"));
        jLabel4.setText(Language.getText("houseTypeLabel"));

        addHousePanelHouseTypeCombo.setBackground(Theme.getColor("fieldBackgroundColor1"));
        addHousePanelHouseTypeCombo.setForeground(Theme.getColor("fieldForegroundColor1"));
        addHousePanelHouseTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GECEKONDU", "APARTMAN", "MÜSTAKİL" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setForeground(Theme.getColor("labelColor1"));
        jLabel5.setText(Language.getText("houseHeatTypeLabel"));

        addHousePanelIsınmaCombo.setBackground(Theme.getColor("fieldBackgroundColor1"));
        addHousePanelIsınmaCombo.setForeground(Theme.getColor("fieldForegroundColor1"));
        addHousePanelIsınmaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MERKEZİ SİSTEM", "KOMBİLİ SİSTEM", "SOBALI SİSTEM" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setForeground(Theme.getColor("labelColor1"));
        jLabel6.setText(Language.getText("houseMonthlyIncomeLabel"));

        addHousePanelGelirCombo.setBackground(Theme.getColor("fieldBackgroundColor1"));
        addHousePanelGelirCombo.setForeground(Theme.getColor("fieldForegroundColor1"));
        addHousePanelGelirCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 - 1000 TL", "1000 - 2000 TL", "2000 TL ve üzeri", "YOK" }));

        addHousePanelAddButton.setBackground(Theme.getColor("buttonBackgroundColor1"));
        addHousePanelAddButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        addHousePanelAddButton.setForeground(Theme.getColor("buttonForegroundColor1"));
        addHousePanelAddButton.setText(Language.getText("addButton"));
        addHousePanelAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHousePanelAddButtonActionPerformed(evt);
            }
        });

        addHousePanelBackButton.setBackground(Theme.getColor("buttonBackgroundColor1"));
        addHousePanelBackButton.setFont(new java.awt.Font("Tahoma", 1, 11));
        addHousePanelBackButton.setForeground(Theme.getColor("buttonForegroundColor1"));
        addHousePanelBackButton.setText(Language.getText("backButton"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addHousePanelAddButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addHousePanelKiraCheck, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addHousePanelHouseNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addHousePanelGelirCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addHousePanelHouseTypeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addHousePanelIsınmaCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 149, Short.MAX_VALUE)
                                        .addComponent(addHousePanelKendiCheck)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(addHousePanelBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))))))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(addHousePanelHouseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addHousePanelKiraCheck)
                    .addComponent(addHousePanelKendiCheck))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addHousePanelHouseTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addHousePanelIsınmaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addHousePanelGelirCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHousePanelAddButton)
                    .addComponent(addHousePanelBackButton))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAddHousePanelBackButton() {
        return addHousePanelBackButton;
    }
/**
 * girilen bilgilere göre hane nesnesi oluşturur ve onu ekler
 * @param evt
 */
    private void addHousePanelAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHousePanelAddButtonActionPerformed

          String houseName = addHousePanelHouseNameField.getText();
          if (houseName.equals(""))
              JOptionPane.showMessageDialog(null, Language.getText("enterHouseNameMessage"));
          else if (!addHousePanelKendiCheck.isSelected() && !addHousePanelKiraCheck.isSelected())
              JOptionPane.showMessageDialog(null, Language.getText("selectHouseStateMessage"));
          else {
              House hane=new House(houseName);
              int point=0;
              if(addHousePanelKiraCheck.isSelected())
                    point=point+5;
              if(addHousePanelKendiCheck.isSelected())
                    point=point+15;
              int index=addHousePanelHouseTypeCombo.getSelectedIndex();
              if(index==0)
                    point=point+10;//gecekondu
              else if(index==1)
                    point=point+20;//apartman
              else if(index==2)
                    point=point+30;//müstakil
              index=addHousePanelIsınmaCombo.getSelectedIndex();
              if(index==0)
                    point=point+15;//merkezi
              else if(index==1)
                    point=point+10;//kombili
		  else if(index==2)
			  point=point+5;//soba
              index=addHousePanelGelirCombo.getSelectedIndex();
              if(index==0)
                    point=point+5;//0-1000
              else if(index==1)
                    point=point+10;//1000-2000
              else if(index==2)
                    point=point+15;//2000-üzeri
		  else if(index==3)
			  point=point+1;//yok
              hane.setHelpPoint(point);
              HouseManager.addHouse(hane);
              JOptionPane.showMessageDialog(null, Language.getText("houseAddedMessage"));
              addHousePanelHouseNameField.setText("");
              addHousePanelKendiCheck.setSelected(false);
              addHousePanelKiraCheck.setSelected(false);
          }
    }//GEN-LAST:event_addHousePanelAddButtonActionPerformed

    private void addHousePanelKiraCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHousePanelKiraCheckActionPerformed
        addHousePanelKendiCheck.setSelected(false);
    }//GEN-LAST:event_addHousePanelKiraCheckActionPerformed

    private void addHousePanelKendiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHousePanelKendiCheckActionPerformed
        addHousePanelKiraCheck.setSelected(false);
    }//GEN-LAST:event_addHousePanelKendiCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHousePanelAddButton;
    private javax.swing.JButton addHousePanelBackButton;
    private javax.swing.JComboBox addHousePanelGelirCombo;
    private javax.swing.JTextField addHousePanelHouseNameField;
    private javax.swing.JComboBox addHousePanelHouseTypeCombo;
    private javax.swing.JComboBox addHousePanelIsınmaCombo;
    private javax.swing.JCheckBox addHousePanelKendiCheck;
    private javax.swing.JCheckBox addHousePanelKiraCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
